#!/bin/bash

# =============================================================
# Constants
# =============================================================

LIQUIBASE_DOCKER_IMAGE=bvz/liquibase-mysql:latest
SERVER_DOCKER_IMAGE=bvz/php:latest
NODE_DOCKER_IMAGE=node:24.12-alpine
COMPOSER_DOCKER_IMAGE=composer/composer
PHPUNIT_DOCKER_IMAGE=jitesoft/phpunit:8.2

DIST_DIR=./dist
DIST_APP_DIR=./dist/app

# =============================================================
# Variables
# =============================================================
PASSWORD=""
NPMX_COMMAND=""

NPM_CONTAINER_NAME="npm_container"
NPM_CONTAINER_RM="--rm"
# =============================================================
# Helpers
# =============================================================

buildBackendForDev() {
    echo "Calling PHP composer for Dev environment"
    docker run --rm \
        --volume ./backend:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE update
    docker run --rm \
        --volume ./backend:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE install
    docker run --rm \
        --volume ./backend:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE dump-autoload
}

buildBackendForIT() {
    echo "Calling PHP composer for IntegrationTest environment"
    cp -r backend/api $DIST_APP_DIR
    cp backend/.env $DIST_APP_DIR
    cp backend/.htaccess $DIST_APP_DIR
    cp backend/composer.json $DIST_APP_DIR
    cp backend/composer.lock $DIST_APP_DIR

    docker run --rm \
        --volume $DIST_APP_DIR:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE install
    docker run --rm \
        --volume $DIST_APP_DIR:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE dump-autoload
}

buildFrontend() {
    echo "Generating the static frontend content."
    NPM_CONTAINER_NAME="build_frontend"
    npm run generate
    cp -r vue/.output/public/* $DIST_APP_DIR
}

buildDbDockerImage() {
    echo "Building the liquibase image for DB Migration"
    docker build --build-arg USER_ID=$(id -u) ./docker/liquibase -t $LIQUIBASE_DOCKER_IMAGE
}

buildServerDockerImage() {
    echo "Building the PHP Server image"
    docker build ./docker/server -t $SERVER_DOCKER_IMAGE
}

buildDist() {
    clean
    mkdir -p ./dist/app

    buildFrontend
    buildBackendForIT

    echo "Optimizing backend imports for Production"
    docker run --rm \
        --volume $DIST_APP_DIR:/app \
        --user $(id -u):$(id -g) \
        $COMPOSER_DOCKER_IMAGE install --prefer-dist --no-dev --optimize-autoloader

    echo "Building distribution"
    zip -rD9 ./dist/app.zip ./dist/app -x "./dist/app/.env*"
}

clean() {
    echo "Cleaning up built files"
    rm -rf $DIST_APP_DIR
    rm $DIST_DIR/app.zip
}

dev() {
    echo "Starting local dev environment"
    USER=$(id -u) GROUP=$(id -g) docker compose --profile dev up -d
}

installFrontend() {
    echo "Setup frontend npm environment"
    docker run -v ./vue:/home/node/app -w /home/node/app -u node $NODE_DOCKER_IMAGE npm install --silent
}

inttest() {
    buildDist

    USER=$(id -u) GROUP=$(id -g) docker compose --profile inttest up -d
}

awaitDbAlive() {
    i=0
    while [[ $i -lt 10 ]]; do
        echo "------ Log check #$((i + 1))/10 ($(date)) ------"
        docker logs --tail 10 brettspielverein-db-1 2>&1 | grep "mysqld: ready for connections."
	    if [[ $? -eq 0 ]]; then
            echo "DB Ready!"
	        return
        fi
        ((i++))
        echo "DB seems to not be ready, will try again in 30 seconds"
        sleep 30
    done
    echo "DB was not ready within 5 minutes!"
    exit 1
}

migrateDevDb() {
    echo "Running DB Migration"
    docker compose --profile db up -d
    awaitDbAlive
    docker run --network=brettspielverein_bvz_network \
        --rm -v ./db/liquibase/changelog:/liquibase/changelog $LIQUIBASE_DOCKER_IMAGE \
        --defaults-file=/liquibase/changelog/liquibase.dev.properties update --changelogFile changelog/root.changelog.yaml
}

migrateProdDb() {
    echo "Running DB PROD Migration"
    docker run --rm -v ./db/liquibase/changelog:/liquibase/changelog $LIQUIBASE_DOCKER_IMAGE \
        --defaults-file=/liquibase/changelog/liquibase.prod.properties update --changelogFile changelog/root.changelog.yaml --password $PASSWORD
}

init() {
    echo "Setup for development"
    buildDbDockerImage
    buildServerDockerImage
    migrateDevDb

    installFrontend

    buildBackendForDev
    cp ./backend/.env.example ./backend/.env
    
    mkdir -p -m 775 logging # required for logging in server
}

stop() {
    USER=$(id -u) GROUP=$(id -g) docker compose --profile "*" down
}

unittest() {
    container_name=php_unit_test
    echo "Running backend tests"
    docker container rm $container_name &> /dev/null
    docker run --name $container_name --user $(id -u):$(id -g) -v ./backend/:/app $SERVER_DOCKER_IMAGE /app/vendor/bin/phpunit --configuration /app/phpunit.xml
    backend_exit_code=$(docker wait $container_name)

    echo "Running frontend tests"
    NPM_CONTAINER_NAME="frontend_unit_test"
    NPM_CONTAINER_RM=""
    docker container rm $NPM_CONTAINER_NAME &> /dev/null
    npm test
    frontend_exit_code=$(docker wait $NPM_CONTAINER_NAME)

    if [[ $backend_exit_code -ne 0 ]]; then
        echo "Backend tests had issues!"
    fi
    if [[ $frontend_exit_code -ne 0 ]]; then
        echo "Frontend tests had issues!"
    fi
    if [[ $frontend_exit_code -eq 0 && $backend_exit_code -eq 0 ]]; then
        echo "All tests passed!"
    fi
}

__hookNodeDockerContainerWithCommand() {
    docker run -v ./vue/:/home/node/app \
        --name $NPM_CONTAINER_NAME \
        $NPM_CONTAINER_RM \
        -w /home/node/app \
        -u node \
        -e NPM_CONFIG_UPDATE_NOTIFIER=false \
        $NODE_DOCKER_IMAGE $@
}

npm() {
    __hookNodeDockerContainerWithCommand npm "$@"
}

npx() {
    __hookNodeDockerContainerWithCommand npx "$@"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]... TARGET <sub-command>

Options:
  -h, --help                Show this help message and exit
  -p <pw>, --password <pw>  Set a password for the prod DB to <pw>

Arguments:
  TARGET                    The task to execute

sub-command:
  Any valid command line that could be given to `npm` or `npx` (e.g. 'install -D sass')

Description:
  This script can be used to execute all relevant task related to building,
  testing and running the website.

  TARGET is a required argument and must be one of the following values:
    - buildDist: Builds the application production ready
    - dev: Starts backend, frontend, DB and mail server in their own containers
    - init: Prepares the project for development, by building required docker images, filling the DB and installing NPM dependencies
    - inttest: Builds the frontend and backend, and deploys them together for testing
    - npm -- <sub-command>: Executes the given <sub-command> for npm, e.g. install -D dependency
    - npx -- <sub-command>: Executes the given <sub-command> for npx, e.g. nuxt prepare
    - migrateDevDb: Apply the current changelog to the Dev DB.
    - migrateProdDb: Apply the current changelog to the PROD DB, requires -p option
    - updateBackend: Update the backend dependencies
    - stop: Stops any running instances.
    - test: Run all frontend and backend tests

  You can combine any options in any order before specifying TARGET.
EOF
}

# =============================================================
# Main part
# =============================================================

target=""

POSITIONAL_ARGS=()

# Parse flags and collect the rest
while [[ $# -gt 0 ]]; do
    case "$1" in
    -h | --help)
        usage
        exit 0
        ;;
    -p | --password)
        shift
        if [[ $# -lt 1 ]]; then
            echo "Error: No password to parse."
            exit 1
        fi
        PASSWORD=$1
        ;;
    --)
        # ${*:2} selects all arguments as a single string, not as multiple arguments
        NPMX_COMMAND="${*:2}"
        break
        ;;
    -*)
        echo "Unknown option: $1"
        usage
        exit 1
        ;;
    *)
        POSITIONAL_ARGS+=("$1")
        shift
        ;;
    esac
done

# Restore positional parameters
set -- "${POSITIONAL_ARGS[@]}"

# Check if final positional argument exists
if [[ $# -lt 1 ]]; then
    echo "Error: Missing mandatory TARGET argument."
    usage
    exit 1
fi

target="$1"
# Validate TARGET
case "$target" in
buildDist)
    buildDist
    ;;
dev)
    dev
    ;;
test)
    unittest
    ;;
inttest)
    inttest
    ;;
init)
    init
    ;;
npm)
    npm "$NPMX_COMMAND"
    docker container rm $NPM_CONTAINER_NAME &>2
    ;;
npx)
    npx "$NPMX_COMMAND"
    docker container rm $NPM_CONTAINER_NAME &>2
    ;;
migrateDevDb)
    migrateDevDb
    ;;
migrateProdDb)
    if [[ -z $PASSWORD ]]; then
        echo "Password required!"
        exit 1
    fi
    migrateProdDb
    ;;
updateBackend)
    buildBackendForDev
    ;;
stop)
    stop
    ;;
*)
    echo "Error: Invalid TARGET value '$target'. Must be one of: buildDist, dev, inttest, init, npm, npx, migrateDevDb, migrateProdDb, stop"
    usage
    exit 1
    ;;
esac
