name: Deploy Test

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-release:
    uses: ./.github/workflows/deploy.yml
    with:
      target: test
    secrets:
      APP_ENV: ${{ secrets.APP_ENV }}
      FTP_USER: ${{ secrets.FTP_USER }}
      FTP_PW: ${{ secrets.FTP_PW }}
      FTP_URL: ${{ secrets.FTP_URL }}
