name: Deploy

on: 
  workflow_call:
    inputs:
      target:
        type: string
        required: true
    secrets:
      APP_ENV:
        required: true
      FTP_USER:
        required: true
      FTP_PW:
        required: true
      FTP_URL:
        required: true

permissions:
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-latest
    environment: Build

    steps:
    - uses: actions/checkout@v4

    - name: Prepare directory
      run: mkdir -p ./dist/app

    - name: Retrieve node build cache
      uses: actions/cache/restore@v4
      id: get-node-cache
      with:
        path: |
          ./vue/node_modules
          ./vue/.nuxt
        key: node_modules-${{ hashFiles('./vue/package-lock.json')}}

    - name: Install frontend dependencies
      if: steps.get-node-cache.outputs.cache-hit != 'true'
      working-directory: vue
      run: npm ci
        npx nuxt generate

    - name: Build frontend
      working-directory: vue
      run: npx nuxt generate

    - name: Cache node build
      if: steps.get-node-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ./vue/node_modules
          ./vue/.nuxt
        key: node_modules-${{ hashFiles('./vue/package-lock.json')}}

    - name: Copy frontend
      run: cp -r vue/.output/public/* ./dist/app/

    - name: Retrieve PHP build cache
      uses: actions/cache/restore@v4
      id: get-php-cache
      with:
        path: |
          ./backend/vendor
        key: php-prod-${{ hashFiles('./dist/app/composer.lock')}}

    - name: Prepare backend files
      if: steps.get-php-cache.outputs.cache-hit != 'true'
      run: |
        cp -r ./backend/api ./dist/app/
        cp ./backend/composer.json ./dist/app/
        cp ./backend/composer.lock ./dist/app/

    - name: Install backend dependencies
      if: steps.get-php-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-dev --optimize-autoloader
      working-directory: ./dist/app

    - name: Store PHP build cache
      if: steps.get-php-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ./dist/app/vendor
        key: php-prod-${{ hashFiles('./dist/app/composer.lock')}}

    - name: Generate Autoload
      run: composer dump-autoload -o
      working-directory: ./dist/app

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: build_no_env
        path: ./dist/app


  release:
    runs-on: ubuntu-latest
    environment: Build
    needs: build-release

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve build
      uses: actions/download-artifact@v5
      with:
        name: build_no_env
        path: ./dist/app

    - name: Extract .env from secrets
      run: mkdir -p dist/app

    - name: Extract .env from secrets
      env: 
        APP_ENV: ${{ secrets.APP_ENV }}
      run: echo -n "$APP_ENV" | base64 -di > dist/app/.env

    - name: Install lftp
      run: sudo apt-get install lftp -y

    - name: Setup lftp connection
      run: lftp -c bookmark add BVZ $FTP_USER:$FTP_PW@$FTP_URL
      env:
        FTP_URL: ${{ secrets.FTP_URL }}
        FTP_USER: ${{ secrets.FTP_USER }}
        FTP_PW: ${{ secrets.FTP_PW }}

    - name: Run backup script
      run: lftp -f scripts/backup_${{ inputs.target }}.lftp

    - name: Upload new version
      run: lftp -f scripts/upload_build_${{ inputs.target }}.lftp
