name: Liquibase

on: workflow_dispatch

permissions:
  contents: read

jobs:
  update-database:
    runs-on: feo-runner-set
    environment: Build

    steps:
    - uses: actions/checkout@v4

    - name: Build liquibase docker container
      run: docker build --build-arg USER_ID=$(id -u) ./docker/liquibase -t bvz/liquibase-mysql:latest

    - name: Run migration
      env: 
        LIQUIBASE_PW: ${{ secrets.LIQUIBASE_PROD_SECRET }}
        LIQUIBASE_USER: ${{ secrets.LIQUIBASE_PROD_USER }}
        LIQUIBASE_URL: ${{ secrets.LIQUIBASE_PROD_URL }}
      run: docker run --rm -v ./db/liquibase/changelog:/liquibase/changelog bvz/liquibase-mysql:latest update --changelogFile ./changelog/root.changelog.yaml --url "$LIQUIBASE_URL" --username "$LIQUIBASE_USER" --password "$LIQUIBASE_PW"

