name: PHP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  setup-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.4"
        tools: phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      working-directory: ./backend

    - name: Restore Composer dev cache packages
      id: composer-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: ./backend/vendor
        key: php-dev-${{ hashFiles('backend/composer.lock') }}

    - name: Install dependencies
      if: steps.composer-cache-restore.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress
      working-directory: ./backend

    - name: Save Composer dev cache packages
      if: steps.composer-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ./backend/vendor
        key: php-dev-${{ hashFiles('backend/composer.lock') }}


  backend-tests:
    runs-on: ubuntu-latest
    needs: setup-backend

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.4"
        tools: phpunit

    - name: Restore Composer dev cache packages
      uses: actions/cache/restore@v4
      with:
        path: ./backend/vendor
        key: php-dev-${{ hashFiles('backend/composer.lock') }}

    - name: Set up .env file
      run: cp .env.example .env
      working-directory: ./backend

    - name: Run test suite
      run: ./vendor/bin/phpunit --configuration phpunit.xml
      working-directory: ./backend

  backend-lint:
    runs-on: ubuntu-latest
    needs: setup-backend

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.4"
        tools: phpunit

    - name: Restore Composer dev cache packages
      uses: actions/cache/restore@v4
      with:
        path: ./backend/vendor
        key: php-dev-${{ hashFiles('backend/composer.lock') }}

    - name: Run linting
      run: ./vendor/bin/phpstan analyse --level=6 api tests
      working-directory: ./backend

